# test code to do word count of a corpus

use CountVectorizer to generate word counts for our corpus

In [1]:
# import sibling utilities
import sys
sys.path.append('../..')

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
infile = "../../dataset/amazon_reviews/amazon_reviews_us_Wireless_v1_00-test-preprocessed.csv"
df = pd.read_csv(infile)

In [6]:
corpus = df["review_body"]
cv = CountVectorizer()
cv_matrix = cv.fit_transform(corpus.array)

vocab = cv.get_feature_names()
print(f'vocab_length: {len(vocab)}')
df = pd.DataFrame(cv_matrix.toarray(), columns=vocab)

df

vocab_length: 718

,ability,able,accessing,accessory,across,activity,actually,add,added,adjust,...,workmanship,worth,would,wrist,wristlet,wrong,year,yes,yet,yr
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
95,0,0,1,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
96,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [16]:
wc_df = pd.DataFrame(df.sum()).reset_index().rename({0: "occurrence", "index": "word"}, axis=1).sort_values("occurrence", ascending=False)
wc_df

        word  occurrence
418      not          38
457    phone          30
270    great          28
486  product          26
705     work          19
..       ...         ...
285     help           1
284   heated           1
282     head           1
281   hassle           1
717       yr           1

[718 rows x 2 columns]